# Generated by Django 4.1.1 on 2022-10-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labelmodel",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Имя"),
        ),
    ]
