# Generated by Django 4.1.1 on 2022-10-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_alter_labelmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
