# Generated by Django 4.1.2 on 2022-10-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='task_manager.userstr', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executor', to='task_manager.userstr', verbose_name='Исполнитель'),
        ),
    ]
