# Generated by Django 4.1.1 on 2022-10-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmodel",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
