# Generated by Django 4.1.1 on 2022-10-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_taskmodel_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="description",
            field=models.CharField(max_length=255),
        ),
    ]
