# Generated by Django 4.1.2 on 2022-10-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskmodel_author_alter_taskmodel_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
