# Generated by Django 4.1.1 on 2022-10-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskmodel_author_alter_taskmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
