# Generated by Django 4.1.1 on 2022-10-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_userstr_delete_user'),
        ('tasks', '0004_alter_taskmodel_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='task_manager.userstr'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executor', to='task_manager.userstr'),
        ),
    ]
