# Generated by Django 4.1.1 on 2022-10-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0002_alter_statusmodel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statusmodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
        ),
    ]
